-- MySQL Script generated by MySQL Workbench
-- Sat May 18 00:38:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema userbanklistdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema userbanklistdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `userbanklistdb` DEFAULT CHARACTER SET utf8 ;
USE `userbanklistdb` ;

-- -----------------------------------------------------
-- Table `userbanklistdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `userbanklistdb`.`user` ;

CREATE TABLE IF NOT EXISTS `userbanklistdb`.`user` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `sureName` VARCHAR(45) NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `userbanklistdb`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `userbanklistdb`.`account` ;

CREATE TABLE IF NOT EXISTS `userbanklistdb`.`account` (
  `accountid` INT NOT NULL AUTO_INCREMENT,
  `account` INT NULL,
  `userid` INT NULL,
  PRIMARY KEY (`accountid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Data for table `userbanklistdb`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `userbanklistdb`;
INSERT INTO `userbanklistdb`.`user` (`userid`, `name`, `sureName`) VALUES (1, 'John', 'Smith');
INSERT INTO `userbanklistdb`.`user` (`userid`, `name`, `sureName`) VALUES (2, 'Alex', 'Johnson');
INSERT INTO `userbanklistdb`.`user` (`userid`, `name`, `sureName`) VALUES (3, 'Bill', 'Murray');
INSERT INTO `userbanklistdb`.`user` (`userid`, `name`, `sureName`) VALUES (4, 'Johnny', 'Depp');
INSERT INTO `userbanklistdb`.`user` (`userid`, `name`, `sureName`) VALUES (5, 'Helen', 'Finkelstein');
INSERT INTO `userbanklistdb`.`user` (`userid`, `name`, `sureName`) VALUES (6, 'Tom', 'Hanks');
INSERT INTO `userbanklistdb`.`user` (`userid`, `name`, `sureName`) VALUES (7, 'Kate', 'Winslet');
INSERT INTO `userbanklistdb`.`user` (`userid`, `name`, `sureName`) VALUES (8, 'Julia', 'Roberts');
INSERT INTO `userbanklistdb`.`user` (`userid`, `name`, `sureName`) VALUES (9, 'Ema', 'Watson');
INSERT INTO `userbanklistdb`.`user` (`userid`, `name`, `sureName`) VALUES (10, 'Daniel', 'Radcliffe');
INSERT INTO `userbanklistdb`.`user` (`userid`, `name`, `sureName`) VALUES (11, 'Rupert', 'Grint');
INSERT INTO `userbanklistdb`.`user` (`userid`, `name`, `sureName`) VALUES (12, 'Britney', 'Spears');

COMMIT;


-- -----------------------------------------------------
-- Data for table `userbanklistdb`.`account`
-- -----------------------------------------------------
START TRANSACTION;
USE `userbanklistdb`;
INSERT INTO `userbanklistdb`.`account` (`accountid`, `account`, `userid`) VALUES (1, 100, 12);
INSERT INTO `userbanklistdb`.`account` (`accountid`, `account`, `userid`) VALUES (2, 500, 11);
INSERT INTO `userbanklistdb`.`account` (`accountid`, `account`, `userid`) VALUES (3, 633, 10);
INSERT INTO `userbanklistdb`.`account` (`accountid`, `account`, `userid`) VALUES (4, 4597, 9);
INSERT INTO `userbanklistdb`.`account` (`accountid`, `account`, `userid`) VALUES (5, 12, 8);
INSERT INTO `userbanklistdb`.`account` (`accountid`, `account`, `userid`) VALUES (6, 1, 7);
INSERT INTO `userbanklistdb`.`account` (`accountid`, `account`, `userid`) VALUES (7, 999, 6);
INSERT INTO `userbanklistdb`.`account` (`accountid`, `account`, `userid`) VALUES (8, 64, 5);
INSERT INTO `userbanklistdb`.`account` (`accountid`, `account`, `userid`) VALUES (9, 222, 4);
INSERT INTO `userbanklistdb`.`account` (`accountid`, `account`, `userid`) VALUES (10, 321, 3);
INSERT INTO `userbanklistdb`.`account` (`accountid`, `account`, `userid`) VALUES (11, 123, 2);
INSERT INTO `userbanklistdb`.`account` (`accountid`, `account`, `userid`) VALUES (12, 492, 1);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
